/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import ConexaoBancoDados.Conexao;

/**
 *
 * @author MARCELO DUARTE
 */
public class Principal extends javax.swing.JFrame {

   Conexao conecta = new Conexao();
   
    
    //ConexaoModificar conectivo = new ConexaoModificar();
    /**
     * Creates new form FormPrincipal
     */
    public Principal() {
        initComponents();
       // conecta.conexaoBanco();
       // conectivo.conexaoBanco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BarraMenuPrincipal = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        Cadastro_Cliente = new javax.swing.JMenuItem();
        Cadastro_Emprestimo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuConsulta = new javax.swing.JMenu();
        Consulta_Cliente = new javax.swing.JMenuItem();
        Consulta_Emprestimo = new javax.swing.JMenuItem();
        MenuRelatorio = new javax.swing.JMenu();
        Relatorio_Cliente = new javax.swing.JCheckBoxMenuItem();
        Relatorio_Emprestimo = new javax.swing.JCheckBoxMenuItem();
        MenuSair = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        MenuCadastro.setText("Cadastro");

        Cadastro_Cliente.setText("Clientes");
        Cadastro_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_ClienteActionPerformed(evt);
            }
        });
        MenuCadastro.add(Cadastro_Cliente);

        Cadastro_Emprestimo.setText("Emprestimo");
        Cadastro_Emprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_EmprestimoActionPerformed(evt);
            }
        });
        MenuCadastro.add(Cadastro_Emprestimo);

        BarraMenuPrincipal.add(MenuCadastro);

        jMenu2.setText("Emprestimo");
        BarraMenuPrincipal.add(jMenu2);

        MenuConsulta.setText("Consulta");

        Consulta_Cliente.setText("Cliente");
        MenuConsulta.add(Consulta_Cliente);

        Consulta_Emprestimo.setText("Emprestimo");
        MenuConsulta.add(Consulta_Emprestimo);

        BarraMenuPrincipal.add(MenuConsulta);

        MenuRelatorio.setText("Relatorio");

        Relatorio_Cliente.setSelected(true);
        Relatorio_Cliente.setText("Cliente");
        MenuRelatorio.add(Relatorio_Cliente);

        Relatorio_Emprestimo.setSelected(true);
        Relatorio_Emprestimo.setText("Emprestimo");
        MenuRelatorio.add(Relatorio_Emprestimo);

        BarraMenuPrincipal.add(MenuRelatorio);

        MenuSair.setText("Sair");
        BarraMenuPrincipal.add(MenuSair);

        setJMenuBar(BarraMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cadastro_EmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_EmprestimoActionPerformed
 
  
    }//GEN-LAST:event_Cadastro_EmprestimoActionPerformed

    private void Cadastro_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_ClienteActionPerformed
CadastroCliente cliente = new CadastroCliente();  
cliente.setVisible(true);
    }//GEN-LAST:event_Cadastro_ClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenuPrincipal;
    private javax.swing.JMenuItem Cadastro_Cliente;
    private javax.swing.JMenuItem Cadastro_Emprestimo;
    private javax.swing.JMenuItem Consulta_Cliente;
    private javax.swing.JMenuItem Consulta_Emprestimo;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuConsulta;
    private javax.swing.JMenu MenuRelatorio;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JCheckBoxMenuItem Relatorio_Cliente;
    private javax.swing.JCheckBoxMenuItem Relatorio_Emprestimo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
